@baseUrl= http://localhost:8080
@shortUrl = b8a897
@id= 5f770e79c825ff5085b8a897
#################################
GET {{baseUrl}}/url/{{shortUrl}} HTTP/1.1
Accept: application/json
#################################
POST {{baseUrl}}/url HTTP/1.1
Content-Type: application/json

{
    "fullUrl": "https://solocoding.dev/blog/eng_docker_buildpacks"
}
#################################
DELETE {{baseUrl}}/url/{{id}} HTTP/1.1